const DEVELOPMENT_KEY = 'eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NjgzNDg3OTksImp0aSI6IjUxY2RmNWM5LWExNDItNDlmZC05MmI0LTE1OTMwOTlmNDI0MyIsImxpY2Vuc2VkSG9zdHMiOlsiMTI3LjAuMC4xIiwibG9jYWxob3N0IiwiMTkyLjE2OC4qLioiLCIxMC4qLiouKiIsIjE3Mi4qLiouKiIsIioudGVzdCIsIioubG9jYWxob3N0IiwiKi5sb2NhbCJdLCJ1c2FnZUVuZHBvaW50IjoiaHR0cHM6Ly9wcm94eS1ldmVudC5ja2VkaXRvci5jb20iLCJkaXN0cmlidXRpb25DaGFubmVsIjpbImNsb3VkIiwiZHJ1cGFsIl0sImxpY2Vuc2VUeXBlIjoiZGV2ZWxvcG1lbnQiLCJmZWF0dXJlcyI6WyJEUlVQIl0sInZjIjoiMTA5ZWVkZGUifQ.7twYmmQ-lQEF3Uh6pJk_rq25LfvdKSDSqXX4kG5HiYi3eGoaMj_zpQJkwfGRLtiFo7Smc4WMw155ypzdsXTAjQ';

const PRODUCTION_KEY = 'eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NjgzNDg3OTksImp0aSI6IjE2YmExOTgyLWI0OTYtNDQwMi05NDUwLThjZWY5NTdmNDBjNCIsInVzYWdlRW5kcG9pbnQiOiJodHRwczovL3Byb3h5LWV2ZW50LmNrZWRpdG9yLmNvbSIsImRpc3RyaWJ1dGlvbkNoYW5uZWwiOlsiY2xvdWQiLCJkcnVwYWwiXSwiZmVhdHVyZXMiOlsiRFJVUCJdLCJ2YyI6IjQ1Y2QyMzI0In0.tjWp7guz42Cx6O4w0zBy5Fi7NHzwsLQa0II7e4OL-rPFugOG3MJDkucuXvkfwclO-qYDkqULHE_bsiaGj6em7Q';

export default function getLicenseKey() {
    const isProduction = window.parent.location.hostname === 'wysiwyg-editors.com';
    const licenseKey = isProduction ? PRODUCTION_KEY : DEVELOPMENT_KEY;

    return licenseKey;
}
